# Generated by Django 6.0.6 on 2026-06-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='models/images/')),
                ('profile', models.TextField(blank=True, help_text='Model bio or description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
