# Generated by Django 6.0.6 on 2026-06-16 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelprofile',
            name='image',
        ),
        migrations.CreateModel(
            name='ModelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='models/images/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.modelprofile')),
            ],
        ),
    ]
