# Generated by Django 6.0.6 on 2026-06-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_modelprofile_image_modelphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='models/main/'),
        ),
    ]
