# Generated by Django 6.0.6 on 2026-06-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_modelprofile_main_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelphoto',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='modelphoto',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
