# Generated by Django 6.0.6 on 2026-06-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelphoto',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Model Photo', 'verbose_name_plural': 'Model Photos'},
        ),
        migrations.AlterModelOptions(
            name='modelprofile',
            options={'ordering': ['id'], 'verbose_name': 'Model Profile', 'verbose_name_plural': 'Model Profiles'},
        ),
    ]
