# Generated by Django 6.0.6 on 2026-06-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_modelphoto_options_alter_modelprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Type your reply to client here', null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, help_text='Auto-filled when you send reply', null=True),
        ),
    ]
