# Generated by Django 6.0.6 on 2026-06-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_contactmessage_user_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='model_photos/'),
        ),
    ]
