"""
Django settings for pro_models project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = config('SECRET_KEY')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS = domains allowed to access Django. Empty = only localhost in dev
ALLOWED_HOSTS = ['pro-models-api.onrender.com', 'localhost', '127.0.0.1']

# ==============================================
# INSTALLED APPS
# Apps Django will load. Order doesn't matter much except adminsortable2 should be before admin
# ==============================================
INSTALLED_APPS = [
    'adminsortable2',  # Lets you drag-drop reorder photos in admin
    'django.contrib.admin',  # Django admin panel at /admin/
    'django.contrib.auth',  # User authentication system
    'django.contrib.contenttypes',  # Content type system
    'django.contrib.sessions',  # Session framework
    'django.contrib.messages',  # Messaging framework
    'django.contrib.staticfiles',  # Handle CSS/JS files
    'api',  # Your app with models/views/serializers
    'rest_framework',
    'rest_framework_simplejwt',  # Django REST Framework for API endpoints
    'corsheaders',  # Allows React frontend to call Django API from different port
]

# ==============================================
# MIDDLEWARE
# Middleware = code that runs on every request/response
# Order matters! CorsMiddleware must be at top for CORS to work
# ==============================================
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Handles CORS headers. Must be first
    'django.middleware.security.SecurityMiddleware',  # Security headers
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # Session management
    'django.middleware.common.CommonMiddleware',  # Common HTTP handling
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF protection. Disabled for API with @api_view
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Attach user to request
    'django.contrib.messages.middleware.MessageMiddleware',  # Message framework
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Clickjacking protection
]

ROOT_URLCONF = 'pro_models.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pro_models.wsgi.application'

# Database - SQLite for development. Use PostgreSQL in production
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation rules
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ==============================================
# STATIC + MEDIA FILES
# Static = CSS/JS files. Media = user uploaded images
# ==============================================


# MEDIA_URL = URL prefix for uploaded images
MEDIA_URL = '/media/'  # URL will be http://localhost:8000/media/models/main/queen.jpg

# MEDIA_ROOT = actual folder on server where images are stored
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Creates 'media' folder in project root

# ==============================================
# CORS SETTINGS - CRITICAL FOR REACT
# CORS = Cross Origin Resource Sharing. Browser blocks requests from port 5173 → 8000 by default
# corsheaders app adds headers to allow it
# ==============================================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite default port - your React app
    "http://localhost:5174",  # Vite alternate port if 5173 is busy
    "http://127.0.0.1:5173",  # Same as localhost but IP format
    "http://127.0.0.1:5174",
]

# For production later, you can use this instead to allow all domains:
# CORS_ALLOW_ALL_ORIGINS = True

# Allow credentials like cookies if you need login later
CORS_ALLOW_CREDENTIALS = True

# ==============================================
# EMAIL SETTINGS - For contact form + admin replies
# ==============================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
  # NO spaces. Get from Google

DEFAULT_FROM_EMAIL = 'Pro Models Studio <agallie962@gmail.com>'
ADMIN_EMAIL = 'agallie962@gmail.com'



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}



STATIC_URL = 'static/'  # URL for CSS/JS: http://localhost:8000/static/style.css

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'