from rest_framework import serializers
from django.contrib.auth.models import User
from .models import ModelProfile, ModelPhoto, ContactMessage, ClientProfile
# ^ Import the 3 models we want to convert to JSON + User + ClientProfile for auth

# ==============================================
# SERIALIZER 1: MODEL PHOTO
# Job: Convert ModelPhoto Django object → JSON dict
# Example: {id: 5, image: "http://...", order: 2}
# ==============================================
class ModelPhotoSerializer(serializers.ModelSerializer):
    # ModelSerializer = auto-generates fields based on ModelPhoto model
    # We just tell it which fields to include
    
    class Meta:
        model = ModelPhoto  # Which Django model this serializer uses
        fields = ['id', 'image', 'order']  # Only send these 3 fields to React
        # 'id' = database ID, 'image' = photo URL, 'order' = sort position

# ==============================================
# SERIALIZER 2: MODEL PROFILE  
# Job: Convert ModelProfile + all its photos → JSON
# Example: {id: 1, name: "Queen", photos: [{...}, {...}]}
# ==============================================
class ModelProfileSerializer(serializers.ModelSerializer):
    # Nested Serializer: Include all photos related to this model
    # many=True = because one model has many photos
    # read_only=True = React can read photos but can't create/update them through this endpoint
    photos = ModelPhotoSerializer(many=True, read_only=True)
    
    # ImageField with use_url=True = send full URL like "http://127.0.0.1:8000/media/models/main/queen.jpg"
    # Without use_url, it would send just the file path
    main_image = serializers.ImageField(use_url=True)

    class Meta:
        model = ModelProfile  # Link to ModelProfile Django model
        # List all fields React needs from API
        fields = ['id', 'name', 'profile', 'main_image', 'photos', 'created_at']
        # React uses these to build the cards + gallery modal

# ==============================================
# SERIALIZER 3: CONTACT MESSAGE - NEW
# Job: Convert ContactMessage Django object → JSON
# Also validates data from React before saving to database
# ==============================================
class ContactMessageSerializer(serializers.ModelSerializer):
    # NEW: Show readable inquiry type instead of 'booking'
    inquiry_type_display = serializers.CharField(source='get_inquiry_type_display', read_only=True)
    
    # ModelSerializer automatically creates validation rules:
    # email field must be valid email format
    # name max_length 100 based on model
    
    class Meta:
        model = ContactMessage  # Link to ContactMessage Django model
        # Fields React sends + fields we send back
        fields = ['id', 'name', 'email', 'phone', 'inquiry_type', 'inquiry_type_display', 
                  'message', 'admin_reply', 'replied_at', 'is_read', 'created_at']
        
        # read_only_fields = React sends these but can't edit them
        # id is auto-generated by database
        # created_at is auto-generated by Django auto_now_add
        read_only_fields = ['id', 'created_at', 'admin_reply', 'replied_at']
        
        # extra_kwargs = add extra rules to fields
        extra_kwargs = {
            'name': {'required': True},  # Must be filled
            'email': {'required': True},  # Must be filled  
            'message': {'required': True},  # Must be filled
            'phone': {'required': False},  # Optional field
        }

# ==============================================
# SERIALIZER 4: USER SIGNUP - NEW
# Job: Handle new user registration
# Validates password match + creates User + ClientProfile
# ==============================================
class SignupSerializer(serializers.ModelSerializer):
    # password2 = extra field to confirm password matches
    password = serializers.CharField(write_only=True, min_length=8, help_text="Min 8 characters")
    password2 = serializers.CharField(write_only=True, help_text="Repeat password")
    phone = serializers.CharField(write_only=True, required=False, allow_blank=True, max_length=20)

    class Meta:
        model = User
        fields = ['id', 'username', 'email', 'password', 'password2', 'first_name', 'last_name', 'phone']
        extra_kwargs = {
            'email': {'required': True},
            'first_name': {'required': False},
            'last_name': {'required': False},
        }

    # Validate that password == password2
    def validate(self, data):
        if data['password'] != data['password2']:
            raise serializers.ValidationError({"password": "Passwords do not match"})
        return data

    # Create user + ClientProfile when signup succeeds
    def create(self, validated_data):
        validated_data.pop('password2')  # remove confirm password
        phone = validated_data.pop('phone', '')  # extract phone for ClientProfile
        
        # create_user hashes password automatically
        user = User.objects.create_user(**validated_data)
        
        # Create linked ClientProfile
        ClientProfile.objects.create(user=user, phone=phone)
        
        return user

# ==============================================
# SERIALIZER 5: USER INFO - NEW
# Job: Show logged-in user info without password
# Used for dashboard + profile page
# ==============================================
class UserSerializer(serializers.ModelSerializer):
    # Pull phone + avatar from related ClientProfile
    phone = serializers.SerializerMethodField()
    avatar = serializers.SerializerMethodField()
    
    
    def get_phone(self, obj):
        if hasattr(obj, "client_profile"):
            return obj.client_profile.phone
        return ""

    def get_avatar(self, obj):
        if hasattr(obj, "client_profile") and obj.client_profile.avatar:
            request = self.context.get("request")
            if request:
                return request.build_absolute_uri(obj.client_profile.avatar.url)
            return obj.client_profile.avatar.url
        return None

    class Meta:
        model = User
        fields = ['id', 'username', 'email', 'first_name', 'last_name', 'phone', 'avatar', 'date_joined']
        read_only_fields = ['id', 'date_joined']
        
        
# ==============================================
# SERIALIZER 6: CLIENT PROFILE UPDATE - NEW
# Job: Allow editing phone + avatar + name
# ==============================================
class ClientProfileUpdateSerializer(serializers.ModelSerializer):
    # We also let them update name/email from User model
    first_name = serializers.CharField(source='user.first_name', required=False)
    last_name = serializers.CharField(source='user.last_name', required=False)
    email = serializers.EmailField(source='user.email', required=False)
    username = serializers.CharField(source='user.username', read_only=True)

    class Meta:
        model = ClientProfile
        fields = ['username', 'email', 'first_name', 'last_name', 'phone', 'avatar']

    def update(self, instance, validated_data):
        user_data = validated_data.pop('user', {})
        user = instance.user
        
        # Update User fields
        user.first_name = user_data.get('first_name', user.first_name)
        user.last_name = user_data.get('last_name', user.last_name)
        user.email = user_data.get('email', user.email)
        user.save()
        
        # Update ClientProfile fields
        return super().update(instance, validated_data)